export const EDITOR_CHANGED = 'PostPage/EDITOR_CHANGED';
export const SEND_POST_REQUESTED = 'PostPage/SEND_POST_REQUESTED';
export const NEW_POST_REQUESTED = 'PostPage/NEW_POST_REQUESTED';

export const FETCH_CATEGORIES_SUCCESS = 'PostPage/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'PostPage/FETCH_CATEGORIES_FAILED';
