export const USER_LOGOUT_REQUEST = 'Admin/USER_LOGOUT_REQUEST';
export const USER_LOGOUT = 'Admin/USER_LOGOUT_REQUEST';

export const TOGGLE_DRAWER = 'Admin/TOGGLE_DRAWER';
export const DRAWER_LINK_CLICKED = 'Admin/DRAWER_LINK_CLICKED';
export const AUTHENTIFICATION_CHECK = 'Admin/AUTHENTIFICATION_CHECK';
export const STORE_USER = 'Admin/STORE_USER';
export const AUTHENTIFICATION_FAILED = 'Admin/AUTHENTIFICATION_FAILED';

