export const FETCH_POST_REQUESTED = 'EditPost/FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCESS = 'EditPost/FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'EditPost/FETCH_POST_FAILED';

export const FETCH_IMAGES_REQUESTED = 'EditPost/FETCH_IMAGES_REQUESTED';
export const FETCH_IMAGES_SUCCESS = 'EditPost/FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILED = 'EditPost/FETCH_IMAGES_FAILED';

export const FETCH_CATEGORIES_REQUESTED = 'EditPost/FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_SUCCESS = 'EditPost/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'EditPost/FETCH_CATEGORIES_FAILED';
