export const FETCH_POST_REQUESTED = 'EditPost/FETCH_POST_REQUESTED';
export const FETCH_POST_SUCCESS = 'EditPost/FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'EditPost/FETCH_POST_FAILED';

export const FETCH_IMAGES_REQUESTED = 'EditPost/FETCH_IMAGES_REQUESTED';
export const FETCH_IMAGES_SUCCESS = 'EditPost/FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILED = 'EditPost/FETCH_IMAGES_FAILED';

export const FETCH_CATEGORIES_REQUESTED = 'EditPost/FETCH_CATEGORIES_REQUESTED';
export const FETCH_CATEGORIES_SUCCESS = 'EditPost/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'EditPost/FETCH_CATEGORIES_FAILED';

export const EDITOR_CHANGED = 'EditPost/EDITOR_CHANGED';

export const EDIT_POST_REQUESTED = 'EditPost/EDIT_POST_REQUESTED';

export const IMAGE_UPLOAD_FINISHED = 'EditPost/IMAGE_UPLOAD_FINISHED';
export const IMAGE_DELETE = 'EditPost/IMAGE_DELETE';

export const OLD_IMAGE_DELETE = 'EditPost/OLD_IMAGE_DELETE';
export const OLD_IMAGE_DEL_REQ = 'EditPost/OLD_IMAGE_DEL_REQ';

export const CLEAR_VALUES_REQUESTED = 'EditPost/CLEAR_VALUES_REQUESTED';

export const ADD_IMAGE_TO_STASH = 'EditPost/ADD_IMAGE_TO_STASH';

