export const FETCH_POSTS_REQUESTED = 'PostsPage/FETCH_POST_REQUESTED';
export const FETCH_POSTS_FAILED = 'PostsPage/FETCH_POSTS_FAILED';
export const FETCH_POSTS_SUCCESS = 'PostsPage/FETCH_POSTS_SUCCESS';

export const EDIT_REQUESTED = 'PostsPage/EDIT_REQUESTED';
export const DELETE_REQIESTED = 'PostsPage/DELETE_REQIESTED';

export const DELETE_CONFIRMED = 'PostsPage/DELETE_CONFIRMED';
export const DELETE_DECLINED = '/DELETE_DECLINED';

export const DELETE_POST_FAILED = 'PostsPage/DELETE_POST_FAILED';
export const DELETE_POST_SUCCESS = 'PostsPage/DELETE_POST_SUCCESS';

