export const FETCH_POSTS_REQUESTED = 'PostsPage/FETCH_POST_REQUESTED';
export const FETCH_POSTS_FAILED = 'PostsPage/FETCH_POSTS_FAILED';
export const FETCH_POSTS_SUCCESS = 'PostPage/FETCH_POSTS_SUCCESS';

