export const CREATE_CATEGORY = 'Category/CREATE_CATEGORY';
export const CREATE_CATEGORY_REQUEST = 'Category/CREATE_CATEGORY_REQUEST';
export const CLOSE_CATEGORY = 'Category/CLOSE_CATEGORY';
export const CREATE_CATEGORY_FAILED = 'Category/CREATE_CATEGORY_FAILED';
export const CREATE_CATEGORY_SUCCESSFUL = 'Category/CREATE_CATEGORY_SUCCESSFUL';
export const STORE_CATEGORY = 'Category/STORE_CATEGORY';


export const FETCH_CATEGORIES = 'Category/FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'Category/FETCH_CATEGORIES_FAILED';
export const FETCH_CATEGORIES_SUCCESS = 'Category/FETCH_CATEGORIES_SUCCESS';

export const SHOW_HIDE = 'Category/SHOW_HIDE';

export const REQUEST_DELETE = 'Category/REQUEST_DELETE';

export const HIDE_MODAL = 'Category/HIDE_MODAL';
export const DELETE_CATEGORY = 'Category/DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'Category/DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'Category/DELETE_CATEGORY_FAILED';
